version: '3.8'

services:
  postgres:
    build: ./docker/postgres
    container_name: postgres_postgis
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: spring_backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: projet-cloud-db
      DB_USER: admin
      DB_PASSWORD: admin

  frontend:
    build: ./frontend
    container_name: frontend_react
    ports:
      - "3000:5173"
    depends_on:
      - backend

  # SERVEUR DE CARTES SIMPLIFIÃ‰
  tileserver:
    image: klokantech/tileserver-gl
    container_name: tileserver
    ports:
      - "8000:80"
    volumes:
      - ./docker/tileserver/data:/data



volumes:
  postgres_data: